## W266 Final Project

In [1]:
import numpy as np
import pandas as pd
import re
import glob #this makes a list of all the files in a directory
from pandasql import sqldf
pysqldf = lambda q: sqldf(q, globals())

In [3]:
files_list = glob.glob("./data/imsdb_scenes_dialogs_nov_2015/dialogs/*/*_dialog.txt")

file_array = np.array(files_list)
files = pd.DataFrame(file_array.reshape(-1,1), columns=["FilePath"])

title_list = []
genre_list = []
for i in files.index:
    genretitle = files['FilePath'][i][45:] #get rid of all the ./data/imsdb...
    a, b = genretitle.split("/")
    genre_list.append(a)
    title_list.append(b[:-11]) #take off '_dialog.txt' from the file name
    
    
files['Genre']=genre_list
files['Title']=title_list

files.head()

                                            FilePath   Genre             Title
0  ./data/imsdb_scenes_dialogs_nov_2015/dialogs/H...  Horror     redridinghood
1  ./data/imsdb_scenes_dialogs_nov_2015/dialogs/H...  Horror     aprilfoolsday
2  ./data/imsdb_scenes_dialogs_nov_2015/dialogs/H...  Horror         hollowman
3  ./data/imsdb_scenes_dialogs_nov_2015/dialogs/H...  Horror  queenofthedamned
4  ./data/imsdb_scenes_dialogs_nov_2015/dialogs/H...  Horror         grudgethe

In [39]:
movie1 = pd.read_fwf('./data/imsdb_scenes_dialogs_nov_2015/dialogs/Adventure/avatar_dialog.txt',
                    header=None, names=["RawLine"],encoding='utf')
movie2 = pd.read_fwf('./data/imsdb_scenes_dialogs_nov_2015/dialogs/Adventure/1492conquestofparadise_dialog.txt',
                    header=None, names=["RawLine"],encoding='utf')
movie1.head(n=15)
### suggestion: always read in movies as UTF-8 so we don't have weird “&amp;amp;”  instead of &

                                     RawLine
0                                     AVATAR
1                                 Written by
2                              James Cameron
3                               VOICE (V.O.)
4           When I was lying there in the VA
5    hospital, with a big hole blown through
6    the middle of my life, I started having
7                    these dreams of flying.
8                               VOICE (V.O.)
9    Sooner or later though, you always have
10                             to wake up...
11                                   CUT TO:
12                               JAKE (V.O.)
13  They can fix a spinal, if you've got the
14    money. But not on vet benefits, not in

In [40]:
def is_name(string):
    #string1 = re.sub('(V.O.)|CUT TO:','',string)
    ### nikki edit
    string1 = re.sub(r'\W+', '', re.sub('(V.O.)|CUT TO:','',string))
    n = re.match('[A-Z][A-Z]+', string1)
    if n: return True
    else: return False

def is_speech(string):
    if not is_name(string):
        return True
    else: return False

def is_cutto(string):
    n = re.match('CUT TO', string)
    #print n
    if n: return True
    else: return False
    

def parse_movie(movie, genre, title):   
#   Args:
#     movie is a pandas dataframe of the raw movie script input
#     genre is the movie genre from the folder it's read in from
#     title is the title (file name prior to _dialog.txt)
#   Output:
#     a dataframe of the form below
    #print genre, title
    curr_char = None
    line = 0
    title_column=[]
    genre_column=[]
    char_column=[]
    speech_column=[]
    line_column=[]
    pkey_column=[]
    for i in movie.index:
        title_column.append(title) 
        genre_column.append(genre) 
        current = str(movie['RawLine'][i])
        #current = str(current)
        #print current
        if current.lower() == 'nan':
            pass
            #print 'stop'

        elif is_cutto(current):
            char_column.append("")
            line_column.append(line)
            speech_column.append("")
            pkey_column.append("")

        elif is_name(current):

            #starting a new character. hold onto this name for the next lines
            #until you see another new character name
            #also try to remove things that are irrelevant to the name 
            ### nikki edit: add in str.strip() in case voice over left whitespaces
            curr_char = re.sub('\(V.O.\)|V.O.|\(O.S.\)|O.S.|\(CONT\'D\)|CONT\'D','',current).strip()
            char_column.append(curr_char)
            pkey_column.append((curr_char+'-'+title).lower().replace(' ', '_'))

            line += 1
            line_column.append(line)
            speech_column.append("")

        elif is_speech(current):

            char_column.append(curr_char)
            line_column.append(line)
            speech_column.append(current)
            if curr_char is not None:
                pkey_column.append((curr_char+'-'+title).lower())
                

    movie['Title']=title_column
    movie['Genre']=genre_column
    movie['Char']=char_column
    movie['LineID']=line_column
    movie['Speech']=speech_column
    movie['pkey']=pkey_column

    return movie



#parse_movie(movie1, 'Adventure', 'avatar')   
#parse_movie(movie2, 'Adventure', '1492conquestofparadise')
parse_movie(movie1, 'Adventure', 'avatar')
movie1.head(n=15)
    
#Intermediate dataframe should look something like this:

#RawLine                                  Title     Genre      Char   LineID     Speech

#JAKE (V.O.)                              Avatar    Adventure  JAKE   1 
#They can fix a spinal, if you've got the Avatar    Adventure  JAKE   1          They can fix... 
#money. But not on vet benefits, not in   Avatar    Adventure  JAKE   1          money. But not...


#And then hopefully we can eventually somehow aggregate by LineID to:

#Title   Genre      Char  Speech
#Avatar  Adventure  JAKE  They can fix a spinal, if you've got the money. But not on vet...

,RawLine,Title,Genre,Char,LineID,Speech,pkey
0,AVATAR,avatar,Adventure,AVATAR,1,,avatar-avatar
1,Written by,avatar,Adventure,AVATAR,1,Written by,avatar-avatar
2,James Cameron,avatar,Adventure,AVATAR,1,James Cameron,avatar-avatar
3,VOICE (V.O.),avatar,Adventure,VOICE,2,,voice-avatar
4,When I was lying there in the VA,avatar,Adventure,VOICE,2,When I was lying there in the VA,voice-avatar
5,"hospital, with a big hole blown through",avatar,Adventure,VOICE,2,"hospital, with a big hole blown through",voice-avatar
6,"the middle of my life, I started having",avatar,Adventure,VOICE,2,"the middle of my life, I started having",voice-avatar
7,these dreams of flying.,avatar,Adventure,VOICE,2,these dreams of flying.,voice-avatar
8,VOICE (V.O.),avatar,Adventure,VOICE,3,,voice-avatar
9,"Sooner or later though, you always have",avatar,Adventure,VOICE,3,"Sooner or later though, you always have",voice-avatar
10,to wake up...,avatar,Adventure,VOICE,3,to wake up...,voice-avatar
11,CUT TO:,avatar,Adventure,,3,,
12,JAKE (V.O.),avatar,Adventure,JAKE,4,,jake-avatar
13,"They can fix a spinal, if you've got the",avatar,Adventure,JAKE,4,"They can fix a spinal, if you've got the",jake-avatar
14,"money. But not on vet benefits, not in",avatar,Adventure,JAKE,4,"money. But not on vet benefits, not in",jake-avatar

In [8]:
movie1['Char'].value_counts()

JAKE                                       757
GRACE                                      434
QUARITCH                                   253
NEYTIRI                                    186
SELFRIDGE                                  137
NORM                                       123
(SUBTITLED)                                119
TRUDY                                       93
                                            87
MAX                                         69
MO'AT                                       63
TSU'TEY                                     55
WAINFLEET                                   33
EYTUKAN                                     18
PILOT                                       17
MED TECH                                    13
CREW CHIEF                                  13
TROOPER                                     11
JAKE (RECORDED)                             10
(QUIETLY)                                    8
VOICE                                        8
(ANGUISHED)                                  8
(MORE)                                       8
(WHISPERING)                                 8
TRUDY (INTERCOM)                             7
GRACE (cont'd)                               7
(NA'VI)                                      7
DISSOLVE TO:                                 6
AGENT 1                                      6
OPERATOR                                     6
                                          ...
(MILDLY)                                     3
I See you.                                   2
FIKE                                         2
PIL                                          2
(ICY)                                        2
WHAM! Total frickin' yard sale. Ate the      2
(PLEADING)                                   2
WHOO-HOOOO!                                  2
SHOULDER)                                    2
MAN                                          2
(INNOCENTLY)                                 2
(YELLING)                                    2
(SOFTENING)                                  2
GUNNER                                       2
(FRUSTRATED)                                 2
I See you, Doctor Grace Augustine.           2
(LAUGHING)                                   2
AGENT 2                                      2
(TURNING)                                    2
GUNSHIP PILOT                                2
(SHOUTING)                                   2
(TRANSLATING)                                2
SLOW DISSOLVE TO:                            1
I See you, Tsu'tey te Rongloa Ateyitan.      1
THEM--                                       1
HERE--                                       1
NEVER!                                       1
TSUTEY                                       1
I See you, Jakesully.                        1
I See you, Neytiri Mo'at'ite.                1
Name: Char, dtype: int64

In [7]:
movie1[movie1["Char"] == 'GRACE']

,RawLine,Title,Genre,Char,LineID,Speech
238,GRACE,avatar,Adventure,GRACE,61,
245,GRACE,avatar,Adventure,GRACE,64,
246,Norm. I hear good things about you.,avatar,Adventure,GRACE,64,Norm. I hear good things about you.
247,How's your Na'vi?,avatar,Adventure,GRACE,64,How's your Na'vi?
248,14.,avatar,Adventure,GRACE,64,14.
253,GRACE,avatar,Adventure,GRACE,66,
261,GRACE,avatar,Adventure,GRACE,71,
262,(turning to Jake),avatar,Adventure,GRACE,71,(turning to Jake)
263,"Yeah, yeah, I know who you are, and I",avatar,Adventure,GRACE,71,"Yeah, yeah, I know who you are, and I"
264,don't need you. I need your brother.,avatar,Adventure,GRACE,71,don't need you. I need your brother.
265,(to Max),avatar,Adventure,GRACE,71,(to Max)
266,You know -- the PhD who trained three,avatar,Adventure,GRACE,71,You know -- the PhD who trained three
267,years for this mission.,avatar,Adventure,GRACE,71,years for this mission.
271,GRACE,avatar,Adventure,GRACE,73,
272,How much lab training have you had? Ever,avatar,Adventure,GRACE,73,How much lab training have you had? Ever
273,run a gas chromatograph?,avatar,Adventure,GRACE,73,run a gas chromatograph?
276,GRACE,avatar,Adventure,GRACE,75,
277,Any actual lab work at all?,avatar,Adventure,GRACE,75,Any actual lab work at all?
280,GRACE,avatar,Adventure,GRACE,77,
281,You see? You see? They're pissing on us,avatar,Adventure,GRACE,77,You see? You see? They're pissing on us
282,without even the courtesy of calling it,avatar,Adventure,GRACE,77,without even the courtesy of calling it
283,rain.,avatar,Adventure,GRACE,77,rain.
284,(turning away),avatar,Adventure,GRACE,77,(turning away)
285,I'm going to Selfridge.,avatar,Adventure,GRACE,77,I'm going to Selfridge.
286,15.,avatar,Adventure,GRACE,77,15.
293,GRACE,avatar,Adventure,GRACE,80,
294,"Parker, I used to think it was benign",avatar,Adventure,GRACE,80,"Parker, I used to think it was benign"
295,"neglect, but now I see you're",avatar,Adventure,GRACE,80,"neglect, but now I see you're"
296,intentionally screwing us.,avatar,Adventure,GRACE,80,intentionally screwing us.
300,GRACE,avatar,Adventure,GRACE,82,
...,...,...,...,...,...,...
2014,you're about to --,avatar,Adventure,GRACE,643,you're about to --
2020,GRACE,avatar,Adventure,GRACE,645,
2021,"For God's sake, there are children in",avatar,Adventure,GRACE,645,"For God's sake, there are children in"
2022,there. Babies!,avatar,Adventure,GRACE,645,there. Babies!
2150,GRACE,avatar,Adventure,GRACE,693,
2151,They never wanted us to succeed.,avatar,Adventure,GRACE,693,They never wanted us to succeed.
2173,GRACE,avatar,Adventure,GRACE,701,
2174,I'm free.,avatar,Adventure,GRACE,701,I'm free.
2194,GRACE,avatar,Adventure,GRACE,708,
2195,Do what he goddamn says!,avatar,Adventure,GRACE,708,Do what he goddamn says!
2201,GRACE,avatar,Adventure,GRACE,711,
2202,"Aaahh, crap. Not again.",avatar,Adventure,GRACE,711,"Aaahh, crap. Not again."
2203,GRACE,avatar,Adventure,GRACE,712,
2204,This is gonna ruin my whole day.,avatar,Adventure,GRACE,712,This is gonna ruin my whole day.
2224,GRACE,avatar,Adventure,GRACE,720,
2225,"Forget it, it doesn't matter.",avatar,Adventure,GRACE,720,"Forget it, it doesn't matter."
2302,GRACE,avatar,Adventure,GRACE,749,
2303,(with a wan smile),avatar,Adventure,GRACE,749,(with a wan smile)
2304,I need to take some samples.,avatar,Adventure,GRACE,749,I need to take some samples.
2319,GRACE,avatar,Adventure,GRACE,756,
2320,I -- always held back. But you gave them,avatar,Adventure,GRACE,756,I -- always held back. But you gave them
2321,"your heart. I'm proud of you, Jake.",avatar,Adventure,GRACE,756,"your heart. I'm proud of you, Jake."
2322,121.,avatar,Adventure,GRACE,756,121.
2323,GRACE,avatar,Adventure,GRACE,757,
2324,Help them. You do whatever it takes. Y,avatar,Adventure,GRACE,757,Help them. You do whatever it takes. Y
2325,hear me?,avatar,Adventure,GRACE,757,hear me?
2328,GRACE,avatar,Adventure,GRACE,759,
2329,I'm with her Jake --,avatar,Adventure,GRACE,759,I'm with her Jake --
2330,(an amazed whisper),avatar,Adventure,GRACE,759,(an amazed whisper)
2331,-- she's real --,avatar,Adventure,GRACE,759,-- she's real --

In [9]:
### keep only characters with at least 20 lines per movie

def top_chars(df, threshold = 20):
    #dframe = df
#     print dframe.head()
#     print type(dframe)
    threshold = threshold
    char_list = pd.DataFrame(df["Char"].value_counts())
    to_remove = char_list[char_list['Char'] <= threshold].index
    cl1 = char_list.drop(to_remove)
    cl1['line_count'] = cl1['Char']
    cl1['Char'] = cl1.index
    #char_list.reset_index(drop=True)
    query = 'SELECT d.*, c.line_count FROM df d INNER JOIN cl1 c on d.Char = c.Char'
    enriched_df = sqldf(query, locals())
    enriched_df = enriched_df[enriched_df['Char'] != '']
    #return cl1.head(20)
    return enriched_df

def pipeline(df,threshold=20):
    ### before top chars, we can add something about a proper title finder
    tc = top_chars(df, threshold)
    
    ### add something about the gender id
    ### add something about vocab enrichment
    ### output should be called final_df
    final_df = tc
    return tc
    

enriched_movie2 = pipeline(movie2)

In [11]:
enriched_movie2.head()

,RawLine,Title,Genre,Char,LineID,Speech,line_count
1,SANCHEZ,1492conquestofparadise,Adventure,SANCHEZ,2,,212
2,Your Majesty would wish to know the,1492conquestofparadise,Adventure,SANCHEZ,2,Your Majesty would wish to know the,212
3,true facts concerning the island of,1492conquestofparadise,Adventure,SANCHEZ,2,true facts concerning the island of,212
4,"Hispanola, our first settlement in",1492conquestofparadise,Adventure,SANCHEZ,2,"Hispanola, our first settlement in",212
5,"the New World, and the activities",1492conquestofparadise,Adventure,SANCHEZ,2,"the New World, and the activities",212

In [12]:
enriched_movie2['Char'].value_counts()

COLUMBUS         825
SANCHEZ          212
MARCHENA         122
AROJAZ           100
PINZON           100
FERNANDO          92
ISABEL            92
SANTANGEL         55
MOXICA            51
AL                44
UTAPAN            40
BEATRIX           38
MENDEZ            32
BOBADILLA         30
BARTOLOME         29
BROTHER BUYL      28
GIACOMO           24
SAILOR            22
ADMINISTRATOR     21
Name: Char, dtype: int64

In [13]:
enriched_movie1 = pipeline(movie1)

In [14]:
enriched_movie1.head()

,RawLine,Title,Genre,Char,LineID,Speech,line_count
1,JAKE (V.O.),avatar,Adventure,JAKE,4,,757
2,"They can fix a spinal, if you've got the",avatar,Adventure,JAKE,4,"They can fix a spinal, if you've got the",757
3,"money. But not on vet benefits, not in",avatar,Adventure,JAKE,4,"money. But not on vet benefits, not in",757
4,this economy.,avatar,Adventure,JAKE,4,this economy.,757
5,JAKE (V.O.),avatar,Adventure,JAKE,6,,757

In [15]:
enriched_movie1['Char'].value_counts()

JAKE           757
GRACE          434
QUARITCH       253
NEYTIRI        186
SELFRIDGE      137
NORM           123
(SUBTITLED)    119
TRUDY           93
MAX             69
MO'AT           63
TSU'TEY         55
WAINFLEET       33
Name: Char, dtype: int64

In [10]:
not_working=[]
char_list_to_label=[]

for i in files_list:
    title = i.split('/')[5].split('_')[0]
    genre = i.split('/')[4]
    if genre=='Western':
        print i
        #print genre
        title = title.strip()
        genre = genre.strip()
        movie = pd.read_fwf("%s" % i,header=None, names=["RawLine"],encoding='utf')
        #print movie
        try:
            parsed = parse_movie(movie, genre, title)
            #print parsed.head()
            final_df = pipeline(movie)
            char_list = final_df.drop_duplicates(subset='Char',keep='last')[['Char','Genre','Title','line_count']]
            char_list_to_label.append(char_list)
        except:
            not_working.append((genre,title))
        #print final_df.head()
        print "processing next movie"
chars= pd.concat(char_list_to_label)
#chars.to_csv('OutputWesternCharacters.csv', index=False)
print not_working
print chars

./data/imsdb_scenes_dialogs_nov_2015/dialogs/Western/djangounchained_dialog.txt
processing next movie
./data/imsdb_scenes_dialogs_nov_2015/dialogs/Western/danceswithwolves_dialog.txt
processing next movie
./data/imsdb_scenes_dialogs_nov_2015/dialogs/Western/bookofelithe_dialog.txt
processing next movie
./data/imsdb_scenes_dialogs_nov_2015/dialogs/Western/tombstone_dialog.txt
processing next movie
./data/imsdb_scenes_dialogs_nov_2015/dialogs/Western/mariachiel_dialog.txt
processing next movie
./data/imsdb_scenes_dialogs_nov_2015/dialogs/Western/baddayatblackrock_dialog.txt
processing next movie
./data/imsdb_scenes_dialogs_nov_2015/dialogs/Western/stationwest_dialog.txt
processing next movie
./data/imsdb_scenes_dialogs_nov_2015/dialogs/Western/wildwildwest_dialog.txt
processing next movie
./data/imsdb_scenes_dialogs_nov_2015/dialogs/Western/truegrit_dialog.txt
processing next movie
./data/imsdb_scenes_dialogs_nov_2015/dialogs/Western/wildbunchthe_dialog.txt
processing next movie
./data/imsdb_scenes_dialogs_nov_2015/dialogs/Western/roughshod_dialog.txt
processing next movie
./data/imsdb_scenes_dialogs_nov_2015/dialogs/Western/tallinthesaddle_dialog.txt
processing next movie
./data/imsdb_scenes_dialogs_nov_2015/dialogs/Western/searchersthe_dialog.txt
processing next movie
[('Western', 'djangounchained'), ('Western', 'bookofelithe'), ('Western', 'wildwildwest')]
                    Char    Genre             Title  line_count
52                PEPPER  Western  danceswithwolves          44
156            FAMBROUGH  Western  danceswithwolves          62
205              CARGILL  Western  danceswithwolves          21
265              TIMMONS  Western  danceswithwolves          46
997               DUNBAR  Western  danceswithwolves         397
1178          STONE CALF  Western  danceswithwolves          27
1292         BLACK SHAWL  Western  danceswithwolves          34
1412               OTTER  Western  danceswithwolves          23
1622      SERGEANT BAUER  Western  danceswithwolves          25
1634              SPIVEY  Western  danceswithwolves          22
1642               ELGIN  Western  danceswithwolves          49
1644        SMILES A LOT  Western  danceswithwolves          49
1659  STANDS WITH A FIST  Western  danceswithwolves         184
1732           TEN BEARS  Western  danceswithwolves         151
1740        KICKING BIRD  Western  danceswithwolves         205
1743  DANCES WITH WOLVES  Western  danceswithwolves         266
1757    WIND IN HIS HAIR  Western  danceswithwolves         153
141    NARRATION (cont.)  Western         tombstone          22
280                 DAKE  Western         tombstone          24
688                TYLER  Western         tombstone          23
1008              FABIAN  Western         tombstone          44
1126         HIGH ROLLER  Western         tombstone          23
1170               WHITE  Western         tombstone          95
1505     OLD MAN CLANTON  Western         tombstone          31
1882                KATE  Western         tombstone          35
1946               JOYCE  Western         tombstone          30
2132              MATTIE  Western         tombstone          76
2294              VIRGIL  Western         tombstone         138
2296               ALLIE  Western         tombstone          28
2355      DR. GOODFELLOW  Western         tombstone          24
...                  ...      ...               ...         ...
3195             JACKSON  Western   tallinthesaddle         139
3205            HAROLDAY  Western   tallinthesaddle         190
3311              GARVEY  Western   tallinthesaddle         260
3316         MISS MARTIN  Western   tallinthesaddle         290
3366               CLARA  Western   tallinthesaddle         155
3384             ROCKLIN  Western   tallinthesaddle         855
3387                ARLY  Western   tallinthesaddle         340
3395                DAVE  Western   tallinthesaddle         528
468                  BEN  Western      searchersthe          29
514               MARTHA  Western      searchersthe          68
524                AARON  Western      searchersthe          90
950                 BRAD  Western      searchersthe          61
1326           FUTTERMAN  Western      searchersthe          48
1751      MARTIN'S VOICE  Western      searchersthe          65
1827             GENERAL  Western      searchersthe          29
1886              KEEFER  Western      searchersthe          33
2131                SCAR  Western      searchersthe          33
2164              EMILIO  Western      searchersthe          59
2499               NESBY  Western      searchersthe          27
2503           JORGENSEN  Western      searchersthe         119
2625      MRS. JORGENSEN  Western      searchersthe         128
2638                MOSE  Western      searchersthe          97
2649          LIEUTENANT  Western      searchersthe          47
2687              LAURIE  Western      searchersthe         184
2766             CHARLIE  Western      searchersthe          75
2816              DEBBIE  Western      searchersthe          70
2825              MARTIN  Western      searchersthe         487
2831               ETHAN  Western      searchersthe         765
2835             CLAYTON  Western      searchersthe         296
2836        DISSOLVE TO:  Western      searchersthe          27

[142 rows x 4 columns]

In [70]:
avatar = parse_movie(movie1, 'Adventure', 'avatar') 
print avatar.head()

                            RawLine   Title      Genre    Char  LineID  \
0                            AVATAR  avatar  Adventure  AVATAR       1
1                        Written by  avatar  Adventure  AVATAR       1
2                     James Cameron  avatar  Adventure  AVATAR       1
3                      VOICE (V.O.)  avatar  Adventure   VOICE       2
4  When I was lying there in the VA  avatar  Adventure   VOICE       2

                             Speech
0
1                        Written by
2                     James Cameron
3
4  When I was lying there in the VA

In [68]:
gender_labels = pd.read_csv('random_sampling_genderized.csv.csv',na_values="NA")
#print gender_labels.count()
#gender_labels = gender_labels[gender_labels['gender'] != 'NA']
#print gender_labels.count()
#gender_labels = gender_labels[gender_labels['gender'] is not None]
#print gender_labels.count()
gender_labels.head(n=40)

gender_labels = gender_labels.dropna(subset=['gender'])
gender_labels['gender'].value_counts()

M    758
F    392
Name: gender, dtype: int64

In [69]:
gender_labels.head()

,id,char,gender,genre,title,line_count,pkey
0,1,WILLY,M,Musical,sisteract,58,willy-sisteract
1,2,ATHOS,M,Action,manintheironmask,378,athos-manintheironmask
2,3,AUGUSTUS,M,Action,perfectcreature,222,augustus-perfectcreature
4,5,JIMMY,M,Romance,mulhollanddrive,43,jimmy-mulhollanddrive
5,6,DENNIS,M,Drama,backdraft,42,dennis-backdraft

In [74]:
all_movies_parsed = []
counter=0
for i in files_list:
    title = i.split('/')[5].split('_')[0]
    genre = i.split('/')[4]
    #print genre
    counter+=1
    print counter
    print i
    title = title.strip()
    genre = genre.strip()
    movie = pd.read_fwf("%s" % i,header=None, names=["RawLine"],encoding='utf')
    #print movie
    try:
        parsed = parse_movie(movie, genre, title)
        #print parsed.head()
        final_df = pipeline(movie)
        all_movies_parsed.append(final_df)
    except:
        pass
all_movies = pd.concat(all_movies_parsed)

print all_movies.head()

1
./data/imsdb_scenes_dialogs_nov_2015/dialogs/Crime/sisteract_dialog.txt
2
./data/imsdb_scenes_dialogs_nov_2015/dialogs/Comedy/sisteract_dialog.txt
3
./data/imsdb_scenes_dialogs_nov_2015/dialogs/Musical/sisteract_dialog.txt
                   RawLine      Title  Genre     Char  LineID  \
0                    VINCE  sisteract  Crime    VINCE      13
1   (half to Christy, half  sisteract  Crime    VINCE      13
2           to the mirror)  sisteract  Crime    VINCE      13
3  You are something else.  sisteract  Crime    VINCE      13
4                  CHRISTY  sisteract  Crime  CHRISTY      14

                    Speech               pkey  line_count
0                             vince-sisteract         231
1   (half to Christy, half    vince-sisteract         231
2           to the mirror)    vince-sisteract         231
3  You are something else.    vince-sisteract         231
4                           christy-sisteract        1234

,RawLine,Title,Genre,Char,LineID,Speech,pkey,line_count
1,JAKE (V.O.),avatar,Action,JAKE,4,,jake-avatar,757
2,"They can fix a spinal, if you've got the",avatar,Action,JAKE,4,"They can fix a spinal, if you've got the",jake-avatar,757
3,"money. But not on vet benefits, not in",avatar,Action,JAKE,4,"money. But not on vet benefits, not in",jake-avatar,757
4,this economy.,avatar,Action,JAKE,4,this economy.,jake-avatar,757
5,JAKE (V.O.),avatar,Action,JAKE,6,,jake-avatar,757

In [90]:
query = 'SELECT m.*, g.gender FROM all_movies m INNER JOIN gender_labels g on m.pkey = g.pkey'
with_gender = sqldf(query, locals())
with_gender = with_gender[with_gender['Char'] != '']
with_gender = with_gender[with_gender['Speech'] != '']
with_gender = with_gender.drop_duplicates(subset=['pkey','LineID','Speech'],keep='last')
with_gender = with_gender.groupby(['gender','Char','Title','Genre','pkey','LineID']).Speech.unique().reset_index()

In [91]:
with_gender

,gender,Char,Title,Genre,pkey,LineID,Speech
0,M,WILLY,sisteract,Musical,willy-sisteract,120,"[I mean, won't she talk? She seemed kind, of u..."
1,M,WILLY,sisteract,Musical,willy-sisteract,125,[Christy?]
2,M,WILLY,sisteract,Musical,willy-sisteract,412,"[It's that call you were expecting,, Vince.]"
3,M,WILLY,sisteract,Musical,willy-sisteract,579,[What? Christy?]
4,M,WILLY,sisteract,Musical,willy-sisteract,582,[Gimme a hand here.]
5,M,WILLY,sisteract,Musical,willy-sisteract,946,"[Yeah, right -- when I see it.]"
6,M,WILLY,sisteract,Musical,willy-sisteract,970,[Go!]
7,M,WILLY,sisteract,Musical,willy-sisteract,979,"[Forget her! We got the one we need!, Step on..."
8,M,WILLY,sisteract,Musical,willy-sisteract,1031,"[She's a nun, Vince.]"
9,M,WILLY,sisteract,Musical,willy-sisteract,1037,"[She's acting weird, Vince. Ever since, we pi..."
10,M,WILLY,sisteract,Musical,willy-sisteract,1048,[She's... she's a nun.]
11,M,WILLY,sisteract,Musical,willy-sisteract,1052,"[She was real quiet and peaceful all the, way ..."
12,M,WILLY,sisteract,Musical,willy-sisteract,1056,"[Right. That way we'd never know which, bulle..."
13,M,WILLY,sisteract,Musical,willy-sisteract,1058,[Got it.]
14,M,WILLY,sisteract,Musical,willy-sisteract,1062,[Neither did you!]
15,M,WILLY,sisteract,Musical,willy-sisteract,1064,"[That's what I figured, too.]"
16,M,WILLY,sisteract,Musical,willy-sisteract,1074,[We both missed.]
17,M,WILLY,sisteract,Musical,willy-sisteract,1078,"[(shocked), Strip down a nun? You want us to ..."
18,M,WILLY,sisteract,Musical,willy-sisteract,1082,[A sweater.]
19,M,WILLY,sisteract,Musical,willy-sisteract,1085,[We got it all worked out.]
20,M,WILLY,sisteract,Musical,willy-sisteract,1089,[What's she doing?]
21,M,WILLY,sisteract,Musical,willy-sisteract,1115,"[There's nuns everywhere! Hundreds of, 'em!]"
22,M,WILLY,sisteract,Musical,willy-sisteract,1123,[Where?]
23,M,WILLY,sisteract,Musical,willy-sisteract,1136,"[Hear that? Now aren't you glad we, didn't sh..."